### ISSUE TITLE
josquin->MEI: dur.quality attribute is not standard

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#1]
I stumbled across this in MEI files coming from Josquin:<br>
`dur.quality="i"`
As a result the command line says: "Unsupported value 'i' for data.DURQUALITY.mensural"
It should be:
`dur.quality="imperfecta"`
See [this file](https://github.com/music-encoding/music-encoding/blob/develop/source/modules/MEI.mensural.xml) from MEI repository.

**Comment by tabourot** [comment]
It was borrowed from some [measuring polyphony](https://measuringpolyphony.org/l) files.
Just fixed. [polenord.ch](https://polenord.ch) produces now the correct values :
`"imperfecta`, `altera`, and `perfecta`.
