### ISSUE TITLE
elastic ligatures

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#13]
Depending on the layout constraint, ligatures should have some horizontal elasticity.

**Comment by lpugin** [comment]
FYI, the `FontInfo` class has now a `m_widthToHeightRatio` member and a `SetWidthToHeightRatio` method, which you can use to scale a glyph. It was added in this commit https://github.com/rism-ch/verovio/commit/9e86fa258d5d94bb5d0eb322059086b098bfc2dd

**Comment by grochat** [comment]
I see, thanks! That should work :-)
