### ISSUE TITLE
josquin->MEI: implement ligatures

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#16]
It seems that many ligatures situations are already covered by verovio as part of MEI (although not yet represented as glyphs)
To take advantage of this, it seems natural in josquin->MEI conversion to group notes in a `<ligature>` tag.

**Comment by lpugin** [comment]
https://www.verovio.org/test-suite.xhtml?cat=ligature is probably a good starting point to see what is currently supported

**Comment by grochat** [comment]
Great! thanks!

**Comment by tabourot** [comment]
Ligatures are already implemented in Vitry's MEI files. It seem's to me that the MEI-mensural syntax can embrass (almost) all cases. The rendition is not the same because, I imagine, it runs verovio 2.6.0. Should I compile 3.0.0 in order to get the same rendition as the testsuite ?

**Comment by lpugin** [comment]
> Should I compile 3.0.0 in order to get the same rendition as the testsuite ?

You need at least 2.7.0

**Comment by lpugin** [comment]
BTW, you can compare versions here https://www.verovio.org/comparison.xhtml

**Comment by grochat** [comment]
Sorry Mr Tabourot, I was confused by an old version of Garison which for some reason did not produce the correct `<ligature>` (via polenord). Everything goes well with `06Garison-IV.txt` !

**Comment by tabourot** [comment]
It was probably a preliminary transcription of Schrade's edition, without ligatures !

**Comment by grochat** [comment]
@Laurent: is there a similar test suite for neumes?.. I am currently working on a MEI->Medieval2 importer that will target both mensural and neumes ;-)

**Comment by lpugin** [comment]
Unfortunately not. However, I am currently merging a contribution for neume rendering. I will ask if they have tests we can include. Of course, it would be great to have your contribution on neumes too!

**Comment by grochat** [comment]
Great! Keep me posted!

**Comment by grochat** [comment]
@lpugin: is there a way to "group" notes with the intention of a ligature without actually drawing it? In that case, notes in manuscripts are left distinct and generally closer to each other than usual.
Maybe through an attribute to `<ligature>`?..
See example, under 'se' or 'na'.
<img width="281" alt="ungroupped_ligature" src="https://user-images.githubusercontent.com/2028669/85410849-e2d39f00-b567-11ea-90d5-991883a866a3.png">

**Comment by grochat** [comment]
Essentially done.
