### ISSUE TITLE
josquin->MEI: create a file with ligature situations

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#18]
It would be extremely useful to have a example file (in josquin format) with all known possible ligature situations (within the corpus of Vitry's motets for instance).
Also, sometimes a ligature can be expressed in several different ways, yet with the same rhythmic meaning, and, to be faithful to the manuscript, we must to be able to encode these discrepancies in josquin.

**Comment by tabourot** [comment]
Find attached to this comment :
David's franconian catalog of ligatures `Notation-Franconienne-Ligatures.pdf`
A "josquin" file with the same systematics `Catalogue_ligatures.txt`. In red, the problematic ligatures.
Some comments on verovio's rendition of that file `Observations_ligatures.txt`.
[Notation-Franconienne-Ligatures.pdf](https://github.com/grochat/verovio/files/4819633/Notation-Franconienne-Ligatures.pdf)
[Catalogue_ligatures.txt](https://github.com/grochat/verovio/files/4819638/Catalogue_ligatures.txt)
[Observations_ligatures.txt](https://github.com/grochat/verovio/files/4819640/Observations_ligatures.txt)

**Comment by grochat** [comment]
Magnifico!

**Comment by tabourot** [comment]
Here a slightly modified version, after David's reading.
[Catalogue_ligatures.txt](https://github.com/grochat/verovio/files/4823702/Catalogue_ligatures.txt)

**Comment by dc1291** [comment]
Why did you enter [[c6 e12]] and not [[c6 d12]] ? The second ascending with return on the left is an interesting graphic problem.

**Comment by tabourot** [comment]
I gave three examples of the pes BL, to show that, presently, verovio chooses between "retour à gauche" and "stem" depending on the interval. The right behaviour would be : by default, display the "retour à gauche" (for all intervals) and, when a stem is josquin-encoded, choose the variant with stem (independent of the interval).

**Comment by grochat** [comment]
Excuse my ignorance, but is there any attributes in MEI-mensural to cover these situations?
And by the way, I think we are missing some MEI attribute `form="disiuncta"` in `<ligature>`, to specify that some melismatic notes should be visually groupped (but not as a ligature strico sensu).

**Comment by lpugin** [comment]
FYI https://github.com/rism-ch/verovio/issues/1516 Please feel free to comment there and in the https://github.com/music-encoding/mensural-ig when problems are MEI related.

**Comment by tabourot** [comment]
According to the last (development) version of the guidelines, the `obliqua` and `recta` parameters are usable, either (for binariae) as a `@form` attribute of the `<ligature>`element, either (for longer ligatures) as a`@lig` attribute of individual notes of the ligature. In addition, josquin adds `@stem.visible`, `@stem.dir`, `@stem.pos` attributes when a "irregular" stem is required. The "regular" stems (i. e. extreme left of the ligature) could (should) be calculed from the note values, without specific encoding. I believe that thes two variables (obliqua and stem) can enclose all imaginable cases.

**Comment by tabourot** [comment]
Concerning "submelismatic" grouping of notes : the precision of our Vitry's encoding goes not so far as delimiting (hypothetical) "submelisms". I would suggest that such considerations be included in the (automatical) spacing algorithm. As a general rule, the standard spacing could be slightly narrower in melisms than in syllabic passages.

**Comment by grochat** [comment]
1. Thanks, I will take the stem attributes into account when I come to ligatures.
2. Yes, the subtle grouping could be automatic in verovio, probably as an option `--beautify-mensural-spacing` or such.
