### ISSUE TITLE
explore line breaks

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#2]
Mensural scores should not be set using "fake" bars (measures), but rather be set like free cadenzas and line breaks.
- is there anything like this in MEI?
- if so, is it taken into account by verovio? (I doubt it).

**Comment by tabourot** [comment]
To the best of my knowledge, MEI-mensural doesn't prescribe the use of bars. But, when compiled by verovio, unmeasured files give unpredictable spacing and line breaks. So, for the moment, [polenord.ch](https://polenord.ch) produces unmeasured files for general use, and artificially measured files for verovio

**Comment by grochat** [comment]
Explore the \<sb\> MEI element (https://music-encoding.org/guidelines/dev/elements/sb.html)

**Comment by tabourot** [comment]
`<sb>` and `<lb>` elements are present in vitry files, as describing the original breaks of the source, but seem to be ignored by verovio (version 2.6.0-dev-a684415).
`[Warning] Element 'lb' is unknown and will be ignored`
`[Warning] Element 'sb' is unknown and will be ignored`

**Comment by grochat** [comment]
Absoloutely mon cher !
We should probably focus of `<sb>` only, don't you think so? In fact `<lb>` seems to be but for pure text and/or karaoke...

**Comment by grochat** [comment]
The best way, so far, seems to use `<barLine form="invis"/>` which is already supported by verovio.

**Comment by lpugin** [comment]
> The best way, so far, seems to use `<barLine form="invis"/>` which is already supported by verovio.

For automatic layout, this is the way to go. Verovio will insert system / page breaks wherever needed but only at places where all voices have a `barLine`.
