### ISSUE TITLE
add new option "favor glyphs"

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#21]
This new option `--favor-glyphs`, off by default, will tell verovio to use glyphs over shapes/polygons whenever possible in mensural (and probably neume) situations, such as ligatures, drawing of maxima, longa, brevis, semibrevis etc.
Linked to #6 and #8.

**Comment by lpugin** [comment]
I would suggest `--use-glyph-mensural` and `--use-glyph-neume` (we already have use-brace-glyph, which should be changed to `--use-glyph-brace`). Does this work for you?

**Comment by grochat** [comment]
Sounds good! So now we have  `--use-glyph-mensural`, `--use-glyph-neume` and `--use-glyph-brace`.
And `--use-brace-glyph` is also kept for backward compatibility ;-)

**Comment by grochat** [comment]
done.
