### ISSUE TITLE
fix brevis rest display (2B, 3B...)

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#25]

**Comment by tabourot** [comment]
In a context of modus perfectus, the longa rest should by default take 3 interlines. With dur="2B", it should take two interlines.

In a context of modus imperfectus, the longa rest shoud ty default take 2 interlines. With dur="3B", it should take three interlines.
[CatalogueSilencesLongues.txt](https://github.com/grochat/verovio/files/10170495/CatalogueSilencesLongues.txt)

**Comment by grochat** [comment]
Thanks! In the context of the Vitry project, would it be possible to always encode longa/brevis rests as 2B or 3B? (in the MEI output file). In fact verovio is structured in a way that makes it almost context-blind, so for instance you don't really know the modus of a specific passage that would give the key for interpreting <rest dur="longa"/>...

**Comment by tabourot** [comment]
Done...
In fact , it only concerns "longa" rests (graphically, "brevis" rests take all one interline, regardless of their duration, and the value "1B" is not defined in MEI !)

**Comment by grochat** [comment]
In the last commit, here is how mensural rests are interpreted:
- "longa" -> 3-space rest
- "3B" -> 3-space rest
- "2B" -> 2-space rest
- "brevis" -> 1-space rest
(no matter the modus...)
Are we happy with this..?

**Comment by tabourot** [comment]
It's fine like this, thank you !
Last commit now on polenord.ch.
Coloration of longa rests definitively disabled.
