### ISSUE TITLE
update/fix ligature algorithm

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#26]
Take (and adapt) Medieval2.5 new ligature code (_NoteSequence::buildGraphicsForLigature()_)

**Comment by tabourot** [comment]
New version of Catalogue_ligatures updated. Red ligatures are badly rendered
[Catalogue_ligatures202212.txt](https://github.com/grochat/verovio/files/10157980/Catalogue_ligatures202212.txt)

**Comment by grochat** [comment]
![tableauLigatures_W_Apel](https://user-images.githubusercontent.com/2028669/206045496-aed7cfa4-97c2-497b-a269-42da47e87bee.jpg)

**Comment by grochat** [comment]
<img width="1006" alt="ligatures_verovio" src="https://user-images.githubusercontent.com/2028669/206174558-f302bfe8-2c4c-4319-bc1d-4ebc49967f6f.png">

[Catalogue_ligatures.mei.txt](https://github.com/grochat/verovio/files/10175819/Catalogue_ligatures.mei.txt)

**Comment by tabourot** [comment]
In the enclosed example (real case), a vertical connector is missing for jumps of sixth interval.
Incidentally (as already known) the beginning of the first ligature should not be oblique.

[connexionLigatureSixte.xml.txt](https://github.com/grochat/verovio/files/10257606/connexionLigatureSixte.xml.txt)

**Comment by grochat** [comment]
That's Medieval 2.5 output. Any comment?
<img width="425" alt="ligature" src="https://user-images.githubusercontent.com/2028669/208548260-89dec0b0-5ee5-408b-8fb8-b659b57e7b4a.png">

**Comment by tabourot** [comment]
For the vertical connectors, that's perfect. But the first segment of the first ligature shouldn't be oblique...

**Comment by tabourot** [comment]
Added last (josquin) version of Catalogue_ligatures, with indication of line width ("latitudo")
[Catalogue_ligatures202212.txt](https://github.com/grochat/verovio/files/10444051/Catalogue_ligatures202212.txt)

**Comment by tabourot** [comment]
Great job !
Only two more small issues, it seems :
-  The stem position for initial longae is blocked on the right.
-  At the beginning of ligatures of more than two notes, verovio systematically displays an oblique, even when a recta is requested.

Cf. file enclosed :
[ligaturesResiduum230129.txt](https://github.com/grochat/verovio/files/10530644/ligaturesResiduum230129.txt)
