### ISSUE TITLE
fix plicas within/at the of a ligature

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#27]

**Comment by grochat** [comment]
example:


<ligature xml:id="V-658">
                  <note xml:id="N-404" stem.visible="true" stem.pos="left" stem.dir="up" dur="semibrevis" oct="4" pname="c" lig="obliqua">
                    <verse xml:id="V-656" n="1" lineid="21">
                      <syl xml:id="V-657" wordpos="t" con="u">se</syl>
                    </verse>
                  </note>
                  <note xml:id="N-405" dur="semibrevis" oct="3" pname="b"/>
                  <note xml:id="N-406" dur="brevis" oct="3" pname="a">
                    <plica dir="up" xml:id="V-660"/>
                  </note>
                </ligature>

**Comment by tabourot** [comment]
when a plica occurs within a ligature, the note head and the left-hand stem should not be drawn, but only the (relatively short) right-hand stem.
Cf. josquin file, verovio's current rendering
 and facsim.

[plique_dans_ligature.txt](https://github.com/grochat/verovio/files/10184283/plique_dans_ligature.txt)


![plicaLig](https://user-images.githubusercontent.com/67205305/206416485-7a4fa179-fce8-4f1d-9aad-d822cc9bca39.png)

![plicaligVerovio](https://user-images.githubusercontent.com/67205305/206418468-58f5646b-6218-4591-ad86-3bb54b059e69.png)

**Comment by grochat** [comment]
Magnifico.
Enclosed is Medieval 2.5 rendering the polenord-conversion to MEI.
<img width="754" alt="plique_dans_ligature_Medieval2 5" src="https://user-images.githubusercontent.com/2028669/206420379-f4fa4609-3fdd-43fc-8418-59227ed1c04e.png">

**Comment by tabourot** [comment]
Medieval 2.5 is right !
