### ISSUE TITLE
display a verse (solmisation) above staff, one way or another

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#29]

**Comment by grochat** [comment]
(ask Laurent Pugin...)

**Comment by grochat** [comment]
Rather than forcing `<div>` or `<dynam>`, another idea would be to use a verse with attribute n="-1", meaning to display it above rather than below the staff. I don't think there is anything against a negative n in MEI...

**Comment by tabourot** [comment]
Exerpt of MEI-mensural documentation
---------------------------------------------------------

in <verse> element :
@n (optional) Provides a number-like designation that indicates an element’s position in a sequence of similar elements. May not contain space characters. Value conforms to [data.WORD](https://music-encoding.org/guidelines/dev/data-types/data.WORD.html).

Definition of data.WORD :  A single "word" that contains only letters, digits, punctuation characters, or symbols. It cannot contain whitespace.

Therefore A negative number matches the definition !

**Comment by grochat** [comment]
@lpugin also suggested to implement `<verse>` attribute `place="above"`. That would probably be even cleaner. - So either way, there is hope!

**Comment by tabourot** [comment]
Agreed !

**Comment by grochat** [comment]
Implemented in commit 8c17339.
Attached in an example.
[MEI_test_verse_above.mei.txt](https://github.com/grochat/verovio/files/10184203/MEI_test_verse_above.mei.txt)
😉 🎼

**Comment by tabourot** [comment]
Just a little bug : since the fourth staff, te lyrics appears underlined. Cf.
[0108Hugo-CMPVBarsSepTriplum-1.pdf](https://github.com/grochat/verovio/files/10188993/0108Hugo-CMPVBarsSepTriplum-1.pdf)
 attached file

**Comment by grochat** [comment]
I have just fixed it by simply disabling syllable extension line  for neume or mensural notation (I hope everyone will agree that makes sense...)
I have noticed that the position of the lyrics "above" depends system-wise on the (variable) position of the lyrics "below". That could be taken care of later... EDIT: just fixed as well.
