### ISSUE TITLE
Some remaining issues with vertical lines

### ISSUE THREAD

**Issue by tabourot** [grochat/verovio#35]
After the finalization of the ligature algorithm, I scanned all the tenors/contratenors in the sources of the first 14 motets and noted some details:
- There are still, for maximae, longae and breves, in or out of the ligatures, required stems that are not displayed.
- For jumps greater than a fifth, the vertical ligature connector is not displayed.
Cf. enclosed file (all real cases with reference)

[ligTenors230130.txt](https://github.com/grochat/verovio/files/10540893/ligTenors230130.txt)

**Comment by grochat** [comment]
Well documented, thank you. It is being taken care of... ;-) Fermons les issues !

**Comment by grochat** [comment]
The last part of the "Connexions" section seems buggy: the MEI output gives a single oct="5" pname="d" longa, which doesn't make sense, I think...

**Comment by tabourot** [comment]
File corrected (missing space between annotation and first note. Indeed, the same case (sixth jump in a ligature)
[ligTenors230130.txt](https://github.com/grochat/verovio/files/10548019/ligTenors230130.txt)
