### ISSUE TITLE
use SmuFL glyphs for mensural durations

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#6]
Currently, simple svg polygons are drawn and SmuFL is not used at all for mensural notes. Those polygons are way too simplistic and ugly (to my taste!)

**Comment by lpugin** [comment]
What do you think about the idea to add an option to enable the use of SMuFL glyphs for mensural notation? It would create some overhead in the code but probably not too much. It would make it an easy way to have your developments continuously integrated.

**Comment by grochat** [comment]
Yes, definitely. And by the way, anything that I am adding (at the moment in a quick-and-dirty way on my fork) is meant to be option-triggered ;-)

**Comment by grochat** [comment]
done.
