### ISSUE TITLE
svg output should keep a trace of the original music font

### ISSUE THREAD

**Issue by grochat** [grochat/verovio#7]
add a `font-origin` attribute to the svg glyph (fonts/extract-glyphs.xsl)

**Comment by lpugin** [comment]
Similar issue discussed here https://github.com/rism-ch/verovio/issues/858#issuecomment-388711752 even though it is more specifically about the fact that we need to make sure the font glyphs embedded in the SVG have a distinct id.

**Comment by grochat** [comment]
Thanks! I would also be tempted to keep track of the original smufl glyph name with a `glyph-name-origin` attribute, but this is probably not a priority!

**Comment by grochat** [comment]
done.
